server:
  port: 8098    
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
      
spring:
  application:
    name: order-service
  liquibase:
      enabled: true
      change-log: classpath:/db/liquibase-changelog.xml
  datasource:
    url: 'jdbc:postgresql://localhost:5432/order'
    username: 'order_account'
    password: 'order_account'
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  banner:
    location: 'classpath:/banner.txt'

